import {anan, steve} from "@/app/(home)/chat/chat.contants";

export const messages = [
  {
    id: 1,
    content: '안녕하세요 아난님!',
    user: anan,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    content: '안녕하세요! ㅎㅎ 오늘은 무엇을 기록하실 건가요?',
    user: steve,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    content: '오늘 날씨가 정말 좋네요!',
    user: anan,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    content: '어제 봤던 영화 너무 재밌었어요!',
    user: steve,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    content: '저는 요리를 시작했어요. 어떤 요리를 추천해주시겠어요?',
    user: anan,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    content: '최근에 읽은 책 중에 좋았던 책이 있나요?',
    user: steve,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7,
    content: '오늘은 어떤 계획이 있으신가요?',
    user: anan,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8,
    content: '좋아하는 음악이 있다면 추천해주세요!',
    user: steve,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9,
    content: '요즘 유행하는 취미가 있을까요?',
    user: anan,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 10,
    content: '휴가 계획 중에 어디를 가려고 생각 중이신가요?',
    user: steve,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 11,
    content: '가장 기억에 남는 여행이 어디인가요?',
    user: anan,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 12,
    content: '요즘에는 어떤 운동을 즐기고 계세요?',
    user: steve,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 13,
    content: '오늘은 무슨 일이 있었나요?',
    user: anan,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 14,
    content: '새로운 레시피를 시도해보고 있어요. 어떤 음식을 좋아하시나요?',
    user: steve,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 15,
    content: '요즘에는 어떤 책을 읽고 계신가요?',
    user: anan,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 16,
    content: '마음에 드는 영화 추천해주세요!',
    user: steve,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 17,
    content: '가장 좋아하는 계절은 무엇인가요?',
    user: anan,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 18,
    content: '음악 장르 중에 어떤 것을 선호하시나요?',
    user: steve,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 19,
    content: '최근에 들은 좋은 소식이 있을까요?',
    user: anan,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 20,
    content: '좋아하는 스포츠가 있나요?',
    user: steve,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 21,
    content: '주말에 어떻게 보내려고 계획 중이신가요?',
    user: anan,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 22,
    content: '가장 감명 깊게 본 영화는 무엇인가요?',
    user: steve,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 23,
    content: '휴식을 취하는 방법 중에 어떤 것이 가장 효과적인가요?',
    user: anan,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 24,
    content: '좋아하는 동물은 무엇인가요?',
    user: steve,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 25,
    content: '가장 기억에 남는 음식은 무엇인가요?',
    user: anan,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 26,
    content: '요즘에는 어떤 기술이나 언어를 배우고 있나요?',
    user: steve,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 27,
    content: '일주일 동안의 하이라이트는 무엇이었나요?',
    user: anan,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 28,
    content: '가장 좋아하는 색은 무엇인가요?',
    user: steve,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 29,
    content: '최근에 듣고 있는 팟캐스트가 있을까요?',
    user: anan,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 30,
    content: '가장 기억에 남는 공연이 어떤 것인가요?',
    user: steve,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 31,
    content: '어떤 종류의 영화를 좋아하시나요?',
    user: anan,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 32,
    content: '요즘에는 어떤 앱이 자주 사용되나요?',
    user: steve,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]