import { Inter } from 'next/font/google'
import './globals.css'
import ThemeProviderCustom from '@/providers/theme.provider'
import { StyledBody } from '@/components/common/common.styles'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <ThemeProviderCustom>
        <StyledBody className={inter.className}>{children}</StyledBody>
      </ThemeProviderCustom>
    </html>
  )
}
